## This file provides default values to modules using the secrets-gradle-plugin. It is necessary
# because the secrets properties file is not under source control so CI builds will fail without
# default values.
SAMPLE_API_KEY=
KEYSTORE_PASSWORD=debug
KEYSTORE_ALIAS=debug
KEYSTORE_PATH=/Users/keystore