package link.apparition.android.sample

import com.startappz.apparition.models.UserData

val EMPTY_USER = UserData(
    appVersion = "",
    referrer = null,
    hardwareId = null,
    isHardwareIdAutoGenerated = false,
    phoneBrand = "",
    phoneModel = "",
    screenDpi = "",
    screenHeight = "",
    screenWidth = "",
    uiMode = "",
    osName = "",
    osVersion = "",
    apiLevel = 0,
    countryCode = "",
    languageCode = "",
    cpuType = null,
    deviceBuildId = "",
    locale = "",
    connectionType = "",
    carrier = null
)