package link.apparition.android.sample

import com.startappz.apparition.models.UserData

val EMPTY_USER = UserData(
    appVersion = "",
    referrer = null,
    hardwareId = null,
    isHardwareIdAutoGenerated = false,
    phoneBrand = "",
    phoneModel = "",
    osName = "",
    osVersion = "",
    apiLevel = 0,
    countryCode = "",
    locale = "",
    connectionType = "",
    carrier = null,
    adId = null
)