@startuml
package "Mobile App" {
    [App Logic]
    [SDK] --> [Expand API]
    [SDK] <-- [Platform Info]
}

package "SDK" {
    component "Initialization" {
        [API Key]
        [User Info Collector]
    }

    component "Deep Link Expansion" {
        [Expand Function]
        [HTTP Client]
    }
}

[Expand API] --> [Backend]
@enduml