# Publish a build for release.
name: KMMBridge-Debug
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  call-publish:
    uses: ./.github/workflows/ios-base-publish.yml
    with:
      build-debug: false